name = "TavaresSonoraPantanoMartinez2025"
uuid = "1b1067e5-e735-420e-a2f7-845b7caa394a"
authors = ["Camila A. Tavares", "Martín Soñora", "Sergio Pantano", "Leandro Martínez"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
Documenter = "1.14.1"
DocumenterTools = "0.1.20"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
